services:
  - type: web
    name: smartshop
    runtime: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      cd frontend && npm install && npm run build && cd ..
    startCommand: gunicorn app:app --timeout 120 --workers 1
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: BREVO_API_KEY
        sync: false
      - key: EMAIL_FROM
        value: impanasubbanna2004@gmail.com
